# Configuration for the typos spell checker utility (<https://github.com/crate-ci/typos>).

[files]
extend-exclude = [
  "nix/kernel.config"
]

[default]
extend-ignore-identifiers-re = [
]

[default.extend-words]

[default.extend-identifiers]

