name: Build

on: [ push, pull_request, merge_group ]

jobs:
  build:
    name: Build Driver with Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: "Build QEMU demo"
        run: nix-build -A runQemuDemo
      - name: "Run QEMU demo"
        run: timeout -s KILL 10s ./result || true
      - name: "Verify write to debugcon device was successful"
        run: "grep 'Hello from User App via /dev/debugcon!' debugcon.txt"
